---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ncdf4)
library(lubridate)
library(ggplot2)
library(tidyverse)
#install.packages("ggthemes")
library(ggthemes)
#install.packages("forecast")
library(forecast)
library(reshape2)
library(zoo)
#install.packages ("ggfortify")
library(ggfortify)
library(magrittr) # needs to be run every time you start R and want to use %>%
library(dplyr)    # alternatively, this also loads %>%
```

```{r}
# write your code and push the changes. then I will merge the files to gether. 

# needed packages ---------------------------------------------------------
# uncomment install lines if you do not have the package and comment them after you are done!
#install.packages("ncdf4")
library(ncdf4) # package for netcdf manipulation
#install.packages("raster")
library(raster) # package for raster manipulation
#install.packages("rgda1")
library(rgdal) # package for geospatial analysis
library(ggplot2) # package for plotting


# reading the data
nc_sst_orig <- nc_open('sstdata_011948_022018.nc')
nc_prec_orig <- nc_open('Pdata_011948_022018-1.nc')

##### sst variables 
zlev <- ncvar_get(nc_sst_orig, "zlev")
# East Longitude (deg)
X_sst <- ncvar_get(nc_sst_orig, "X")
print (dim(X_sst))
# time from Jan. 1948 to Feb. 2018 
# 12*(2018-1948)+1(Jan 2018)+1(Feb 2018) = 842
time_sst <- ncvar_get(nc_sst_orig, "T")
print (dim(time_sst))
# Latitude (deg)
Y_sst <- ncvar_get(nc_sst_orig, "Y")
print (dim(Y_sst))
sst_anom <- ncvar_get(nc_sst_orig, "anom")
print (dim(sst_anom))
jpeg("sst_Feb2018.png", width=1600, height=1600, res=300)
image(x=X_sst, y=Y_sst, z=sst_anom[,,842], 
      col = hcl.colors(12, "YlOrRd", rev = TRUE),
      xlab="East Longitude (deg)",
      ylab="Latitude (deg)", main="sst Anomalies: Feb 2018")
dev.off()

##### precipitation variables
# East Longitude (deg)
X_prec <- ncvar_get(nc_prec_orig, "X")
print (dim(X_prec))
# time 
time_prec <- ncvar_get(nc_prec_orig, "T")
print (dim(time_prec))
# Latitude (deg)
Y_prec <- ncvar_get(nc_prec_orig, "Y")
print (dim(Y_prec))
# Precipitation
prec <- ncvar_get(nc_prec_orig, "rain")
# reproduce the image in file
jpeg("prec_Feb2018.png", width=1600, height=1600, res=300)
image(x=X_prec, y=Y_prec, z=prec[,,842], 
      col = hcl.colors(12, "YlOrRd", rev = TRUE),
      xlab="West Longitude (deg)",
      ylab="Latitude (deg)", main="Precipitation: Feb 2018")
dev.off()

```
# explanatory 

```{r}
############## explanatory
# prec is a tensor that has 842 (months)matrices of size [x=120,y=50]
# convert the time to year
time_sst1 = time_sst * 30.42
time_sst2 <- as.Date(time_sst1, origin="1960-1-1 00:00", tz="UTC")

time_prec1 = time_prec * 30.42
time_prec2 <- as.Date(time_prec1, origin="1960-1-1 00:00", tz="UTC")

prec_mean <- apply(prec, 3, mean,na.rm=TRUE)
tempseries <- data.frame(year=time_prec2,prec=prec_mean)

jpeg("mean_prec_monthly.png", width=1600, height=1000, res=300)
tempseries %>% ggplot(aes(x=year,y=prec))+geom_line()+
   labs(title = "Monthly mean precipitation from Jan. 1948 to Feb. 2018", x="year",y="Precipitation")
dev.off()

jpeg("mean_sst_monthly.png", width=1600, height=1000, res=300)
sst_mean <- apply(sst_anom, 3, mean,na.rm=TRUE)
tempseries <- data.frame(year=time_sst2, temperature=sst_mean)
tempseries %>% ggplot(aes(x=year,y=temperature))+geom_line()+
   labs(title = "Monthly mean Temp. [Jan. 1948 to Feb. 2018]", x="year",y="SST anamolies")
dev.off()

# create a dataset with months_year and ids
months <- c(rep(seq(1,12),842/12),1,2)
month_name <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
months_name <- c(rep(month_name,842/12), "Jan", "Feb")
ids <- seq(1,842)
year <- seq(1948,2018)
years <- list()
counter=1
for (y in year){
   for (i in seq(1,12)){
      years[counter] = y
      counter = counter+1
   }
}
years <- years[1:842]
years <- do.call(rbind.data.frame, years)
colnames(years) <- c('year')

months_years_id <- data.frame (ids, months, months_name)
months_years_id ["year"] = years
months_years_id ["prec_mean"] <- prec_mean

#temperature for each month
tempseries <- data.frame(year=time_prec2,sst=sst_mean)
month_mean_sst = rep(0, 12)
for (i in 1:nrow(tempseries))
{
   month = as.numeric(substr(as.character(tempseries[i,1]),6,7))
   month_mean_sst[month] = month_mean_sst[month] + abs(tempseries[i,2])
}
# you need to get the average
months_count = c(71, 71, rep(70,10))
month_mean_sst <- month_mean_sst/months_count
month_mean_sst = data.frame(month_num=factor(c(1:12)),
                            month_name=month_name, sst=month_mean_sst)

jpeg("Months_allyears_SST.png", width=1600, height=1000, res=300)
ggplot(month_mean_sst, aes(x=factor(month_num),y=sst))+
   geom_point(aes(x=month_num,y=sst)) + 
   scale_x_discrete(breaks = factor(c(1:12)), labels=month_name) + 
   labs(title = "Mean SST for each month", x="month",y="Temperature" )
dev.off()
#Prec for each month
tempseries <- data.frame(year=time_prec2,prec=prec_mean)
month_mean_prec = rep(0, 12)
for (i in 1:nrow(tempseries))
{
   month = as.numeric(substr(as.character(tempseries[i,1]),6,7))
   month_mean_prec[month] = month_mean_prec[month] + abs(tempseries[i,2])
}
# you need to get the average
months_count = c(71, 71, rep(70,10))
month_mean_prec <- month_mean_prec/months_count

month_mean_prec = data.frame(month_num=factor(c(1:12)), prec=month_mean_prec, 
                             month_name=month_name)
jpeg("Months_allyears_prec.png", width=1600, height=1000, res=300)
ggplot(month_mean_prec, aes(x=factor(month_num),y=prec))+
   geom_point(aes(x=month_num,y=prec)) + 
   scale_x_discrete(breaks = c(1:12), labels=month_name) +  
   labs(title = "Mean Precipitation for each month", x="month",y="Precipitation")
dev.off()
# dimension reduction


# Clustering


# prediction
prec_s1 <- which(is.na(prec[,,1]))
prec_s2 <- which(!is.na(prec[,,1]))
prec_sst <- matrix(0, nrow = dim(prec)[3], ncol = length(prec_s2))
for(i in 1:dim(prec)[3])
   prec_sst[i,] <- prec[,,i][-prec_s1]
prec_eof <- svd(prec_sst)$v
loc <- as.matrix(expand.grid(x = X_prec, Y_prec = Y_prec))[prec_s2,]
coltab <- colorRampPalette(brewer.pal(9,"BrBG"))(2048)
# plot the first EOF
par(mfrow=c(1,1))
quilt.plot(loc, prec_eof[,1], nx = length(X_prec), 
           ny = length(Y_prec), xlab = "longitude",
           ylab = "latitude", 
           main = "1st EOF", col = coltab,
           cex.lab = 3, cex.axis = 3, cex.main = 3,
           legend.cex = 20)
maps::map(database = "world", fill = TRUE, col = "gray", 
          ylim=c(-35, 35), xlim = c(123.9,290.1), add = T)

# plot the second EOF
par(mar = c(5,5,3,3), oma=c(1,1,1,1))
quilt.plot(loc, prec_eof[,2], nx = length(X_prec), 
           ny = length(Y_prec), xlab = "longitude",
           ylab = "latitude", 
           main = "2nd EOF", col = coltab,
           cex.lab = 3, cex.axis = 3, cex.main = 3,
           legend.cex = 20)
maps::map(database = "world", fill = TRUE, col = "gray", 
          ylim=c(-35, 35), xlim = c(123.9,290.1), add = T)

lon_prec <- ncvar_get(nc_prec_orig,"X")
lat_prec <- ncvar_get(nc_prec_orig,"Y")
time_prec <- ncvar_get(nc_prec_orig,"T")
time_prec = time_prec * 30.42
time_prec <- as.Date(time_prec, origin="1960-1-1 00:00", tz="UTC")
prec_mean <- apply(prec,3,mean,na.rm=TRUE)
tempseries <- data.frame(year=time_prec,prec=prec_mean)
tempseries %>% ggplot(aes(x=year,y=prec))+geom_line()+labs(title = "Monthly mean Precipitation from January 1948 to Feburary 2018", x="year",y="Precipitation" )
mov_avg <- tempseries %>% select(year, prec) %>% mutate(prec_1yr = rollmean(prec, k = 13, fill = NA, align = "right"), prec_5yr = rollmean(prec, k = 61, fill = NA, align = "right"))
mov_avg %>% gather(key="metrice",value = "value",prec:prec_5yr)%>% ggplot(aes(x=year,y=value,col=metrice))+
   geom_line()+scale_color_manual(values = c("bisque4","darkred","blue"),labels=c("Monthly mean","Annual mean","5 years moving Average"))+
   scale_x_date(limits =ymd(c("1948-01-01","2018-01-01")) ,breaks = seq(ymd("1948-01-01"),ymd("2018-01-01"),"10 years"),date_labels ="%Y")+ 
   scale_y_continuous(breaks = seq(23,33,0.5))+labs( x="year",y="SST [°C]" )+
   theme_clean(base_size = 12,)+
   theme(legend.title = element_blank(),legend.position = c("top"),legend.direction = "horizontal")
```

